# Лараторная работа №1
## Выполнил студент группы БСТ1904 Голованов В.Д.

In [1]:
print("Hello World!")

Hello World!


# Задание №2
## Написать генератор случайных матриц(многомерных), который принимает
## опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
## матрицы, а min_lim и max_lim - минимальное и максимальное значение для
## генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
## значения:
## m = 50
## n = 50
## min_limit = -250
## max_limit = 1000 + 4

In [3]:
import numpy as np
import random
try:
    m = int(input("Введите количество строк:"))
except ValueError:
    m = 50
try:
    n = int(input("Введите число столбцов:"))
except ValueError:
    n = 50
try:
    min_limit = int(input("Введите минимальное число:"))
except ValueError:
    min_limit  = -250
try:
    max_limit = int(input("Введите максимальное число:"))
except ValueError:
    max_limit = 1004
genMass = np.empty([m,n])
for i in range(m):
    for j in range(n):
        genMass[i,j] = random.randint(min_limit, max_limit)
print(genMass)


Введите количество строк: 4
Введите число столбцов: 4
Введите минимальное число: -32
Введите максимальное число: 98


[[ 64.  20.  87.  94.]
 [-31. -14.  87.  84.]
 [-12.  46.  50.  14.]
 [ -5.  81.  70.   8.]]


## Задание №3
## Реализовать методы сортировки строк числовой матрицы в соответствии с
## заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
## временем стандартной функции сортировки. Испытания проводить на сгенерированных
## матрицах.

In [8]:
%%time
import numpy as np
def InsertionSort(genMass): 
    for i in range(1, len(genMass)): 
        new_elem = genMass[i] 
        j = i - 1 
        while j >= 0 and genMass[j] > new_elem: 
            genMass[j + 1] = genMass[j] 
            j -= 1 
        genMass[j + 1] = new_elem
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
InsertionSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[-31. -14. -12.  -5.]
 [  8.  14.  20.  46.]
 [ 50.  64.  70.  81.]
 [ 84.  87.  87.  94.]]
Wall time: 0 ns


In [9]:
%%time
import numpy as np
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
sortMass.sort()
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[-31. -14. -12.  -5.]
 [  8.  14.  20.  46.]
 [ 50.  64.  70.  81.]
 [ 84.  87.  87.  94.]]
Wall time: 14 ms
