# Лараторная работа №1
 Выполнил студент группы БСТ1904 Голованов В.Д.

In [1]:
print("Hello World!")

Hello World!


# Задание №2
 Написать генератор случайных матриц(многомерных), который принимает
 опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
 матрицы, а min_lim и max_lim - минимальное и максимальное значение для
 генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
 значения:
 m = 50
 n = 50
 min_limit = -250
 max_limit = 1000 + 4

In [8]:
import numpy as np
import random
try:
    m = int(input("Введите количество строк:"))
except ValueError:
    m = 50
try:
    n = int(input("Введите число столбцов:"))
except ValueError:
    n = 50
try:
    min_limit = int(input("Введите минимальное число:"))
except ValueError:
    min_limit  = -250
try:
    max_limit = int(input("Введите максимальное число:"))
except ValueError:
    max_limit = 1004
genMass = np.empty([m,n])
for i in range(m):
    for j in range(n):
        genMass[i,j] = random.randint(min_limit, max_limit)
print(genMass)

Введите количество строк: 4
Введите число столбцов: 5
Введите минимальное число: -12
Введите максимальное число: 42


[[ 18.  25.   6.  28.  40.]
 [  5.  10.  39.  30.  20.]
 [-12.  37.  15.  38.  35.]
 [ 13.   3.  38.  21.  -4.]]


## Задание №3
 Реализовать методы сортировки строк числовой матрицы в соответствии с
 заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
 временем стандартной функции сортировки. Испытания проводить на сгенерированных
 матрицах.

In [ ]:
%%time
import numpy as np
def InsertionSort(genMass): 
    for i in range(1, len(genMass)): 
        new_elem = genMass[i] 
        j = i - 1 
        while j >= 0 and genMass[j] > new_elem: 
            genMass[j + 1] = genMass[j] 
            j -= 1 
        genMass[j + 1] = new_elem
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
InsertionSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

In [ ]:
%%time
import numpy as np
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
sortMass.sort()
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

In [ ]:
%%time
import numpy as np
def selectionSort(genMass): 
    for i in range(0, len(genMass) - 1): 
        for j in range(i + 1, len(genMass)): 
            if genMass[j] < genMass[i]: 
                genMass[i], genMass[j] = genMass[j], genMass[i]
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
InsertionSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

In [ ]:
%%time
import numpy as np
def selectionSort(genMass):
    for i in range(len(genMass) - 1):
        m = i
        j = i + 1
        while j < len(genMass):
            if genMass[j] < genMass[m]:
                m = j
            j = j + 1
        genMass[i], genMass[m] = genMass[m], genMass[i]
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
selectionSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

In [ ]:
%%time
import numpy as np
def bubbleSort(genMass): 
    for j in range(len(genMass) - 1, 0, -1): 
        for i in range(0, j): 
            if genMass[i] > genMass[i + 1]: 
                genMass[i], genMass[i + 1] = genMass[i + 1], genMass[i]
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
bubbleSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

In [9]:
%%time
import numpy as np
def shellSort(genMass):
    gap = len(genMass) // 2
    while gap > 0:
        for i in range (len(genMass)):
            j = i + gap
            for j in range (len(genMass)):
                if genMass[i] < genMass[j]:
                    genMass[i], genMass[j] = genMass[j], genMass[i]
        gap //= 2
    
        
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
shellSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[-12.  -4.   3.   5.   6.]
 [ 10.  13.  15.  18.  20.]
 [ 21.  25.  28.  30.  35.]
 [ 37.  38.  38.  39.  40.]]
Wall time: 999 µs


In [12]:
%%time
import numpy as np
def quickSort(genMass):
    if len(genMass) <= 1:
        return genMass
    else:
        q = genMass[0]
        L = [elem for elem in genMass if elem < q]
        M = [q] * genMass.count(q)
        R = [elem for elem in genMass if elem > q] 
        return QuickSort(L) + M + QuickSort(R)
    
        
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
quickSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

AttributeError: 'numpy.ndarray' object has no attribute 'count'