# Лараторная работа №1
 Выполнил студент группы БСТ1904 Голованов В.Д.

In [1]:
print("Hello World!")

Hello World!


# Задание №2
 Написать генератор случайных матриц(многомерных), который принимает
 опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
 матрицы, а min_lim и max_lim - минимальное и максимальное значение для
 генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
 значения:
 m = 50
 n = 50
 min_limit = -250
 max_limit = 1000 + 4

In [5]:
import numpy as np
import random
try:
    m = int(input("Введите количество строк:"))
except ValueError:
    m = 50
try:
    n = int(input("Введите число столбцов:"))
except ValueError:
    n = 50
try:
    min_limit = int(input("Введите минимальное число:"))
except ValueError:
    min_limit  = -250
try:
    max_limit = int(input("Введите максимальное число:"))
except ValueError:
    max_limit = 1004
genMass = np.empty([m,n])
for i in range(m):
    for j in range(n):
        genMass[i,j] = random.randint(min_limit, max_limit)
print(genMass)

Введите количество строк: 29
Введите число столбцов: 12
Введите минимальное число: -1
Введите максимальное число: 10


[[ 5. -1.  9.  7.  3.  3.  1.  9.  8.  0.  2.  4.]
 [ 3.  9.  9.  1.  4.  1.  0.  9.  0. -1.  7.  9.]
 [-1.  2.  3.  9.  0.  3.  7.  4.  2. -1.  5.  4.]
 [-1.  7.  3.  3.  4.  2.  9. -1.  6.  8. 10.  7.]
 [ 4.  7.  2.  8.  6.  9.  6.  9.  0. -1.  6.  6.]
 [ 8.  0.  4.  8.  7.  4.  0. 10.  8.  6.  4.  1.]
 [ 6.  6.  7.  5.  6. 10. 10.  8.  7.  7. -1.  8.]
 [ 6.  9.  3.  2.  0.  8.  4. -1.  8.  6.  3. -1.]
 [ 8.  2.  3.  7.  1.  9.  1.  7.  7. 10.  6.  7.]
 [-1. 10.  8.  6.  8.  6.  3.  9.  6.  8.  9.  1.]
 [ 4. 10.  4.  7.  3. 10. 10.  3.  4.  4.  9.  4.]
 [ 0.  9. -1.  6.  1.  4.  7.  9.  0.  6.  5.  5.]
 [ 3. -1.  9.  6.  4. -1.  3.  9.  2.  8.  1.  1.]
 [ 2.  6.  9.  5.  5.  0.  1.  5.  3.  9.  1.  2.]
 [10.  6.  0.  6.  0. 10.  9.  9.  8.  2.  4.  5.]
 [ 4. -1. 10. -1.  3.  1.  2. -1.  0.  2.  3.  2.]
 [ 9.  9.  7.  7.  4.  3. -1.  0.  1. -1.  7. 10.]
 [ 0.  4.  3.  0.  3.  1. 10.  6.  3.  4.  8. -1.]
 [ 9.  1. 10.  9.  9. 10. 10.  1.  0.  6.  4. -1.]
 [ 2.  8.  7.  0.  8.  1. -1.  

## Задание №3
 Реализовать методы сортировки строк числовой матрицы в соответствии с
 заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
 временем стандартной функции сортировки. Испытания проводить на сгенерированных
 матрицах.

In [2]:
%%time
import numpy as np
def insertionSort(genMass): 
    for i in range(1, len(genMass)): 
        new_elem = genMass[i] 
        j = i - 1 
        while j >= 0 and genMass[j] > new_elem: 
            genMass[j + 1] = genMass[j] 
            j -= 1 
        genMass[j + 1] = new_elem
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
insertionSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[4. 4. 4.]
 [5. 5. 8.]]
Wall time: 8 ms


In [5]:
%%time
import numpy as np
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
sortMass.sort()
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[-27. -21.]
 [ -2.  10.]
 [ 30.  35.]]
Wall time: 33.1 ms


In [6]:
%%time
import numpy as np
def selectionSort(genMass):
    for i in range(len(genMass) - 1):
        m = i
        j = i + 1
        while j < len(genMass):
            if genMass[j] < genMass[m]:
                m = j
            j = j + 1
        genMass[i], genMass[m] = genMass[m], genMass[i]
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
selectionSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[-27. -21.]
 [ -2.  10.]
 [ 30.  35.]]
Wall time: 0 ns


In [7]:
%%time
import numpy as np
def bubbleSort(genMass): 
    for j in range(len(genMass) - 1, 0, -1): 
        for i in range(0, j): 
            if genMass[i] > genMass[i + 1]: 
                genMass[i], genMass[i + 1] = genMass[i + 1], genMass[i]
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
bubbleSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[-27. -21.]
 [ -2.  10.]
 [ 30.  35.]]
Wall time: 0 ns


In [3]:
%%time
import numpy as np
def shellSort(genMass):
    gap = len(genMass) // 2
    while gap > 0:
        for i in range (len(genMass)):
            j = i + gap
            for j in range (len(genMass)):
                if genMass[i] < genMass[j]:
                    genMass[i], genMass[j] = genMass[j], genMass[i]
        gap //= 2
    
        
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
shellSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[13. 14. 17. 19. 20. 26. 29. 30.]
 [30. 30. 31. 31. 31. 32. 33. 34.]
 [35. 36. 36. 40. 42. 42. 43. 43.]
 [44. 45. 46. 47. 47. 49. 49. 50.]]
Wall time: 8.19 ms


In [10]:
import numpy as np
def quickSort(Arr, start, end):
    if end - start > 1:
        p = partition(Arr, start, end)
        quickSort(Arr, start, p)
        quickSort(Arr, p + 1, end)
 
 
def partition(Arr, start, end):
    pivot = Arr[start]
    i = start + 1
    j = end - 1
 
    while True:
        while (i <= j and Arr[i] <= pivot):
            i = i + 1
        while (i <= j and Arr[j] >= pivot):
            j = j - 1
 
        if i <= j:
            Arr[i], Arr[j] = Arr[j], Arr[i]
        else:
            Arr[start], Arr[j] = Arr[j], Arr[start]
            return j
 
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
quickSort(sortMass, 0, len(genMass))
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[ 1.  7.]
 [13. 16.]
 [17. 17.]
 [26. 27.]]


In [5]:
import numpy as np
def heapSort(Arr):
    build_max_heap(Arr)
    for i in range(len(Arr) - 1, 0, -1):
        Arr[0], Arr[i] = Arr[i], Arr[0]
        max_heapify(Arr, index=0, size=i)
        
def parent(i):
    return (i - 1)//2
 
def left(i):
    return 2*i + 1
 
def right(i):
    return 2*i + 2
 
def build_max_heap(Arr):
    length = len(Arr)
    start = parent(length - 1)
    while start >= 0:
        max_heapify(Arr, index=start, size=length)
        start = start - 1
        
def max_heapify(Arr, index, size):
    l = left(index)
    r = right(index)
    if (l < size and Arr[l] > Arr[index]):
        largest = l
    else:
        largest = index
    if (r < size and Arr[r] > Arr[largest]):
        largest = r
    if (largest != index):
        Arr[largest], Arr[index] = Arr[index], Arr[largest]
        max_heapify(Arr, largest, size)
 
 
sortMass = np.empty([m*n])
z = 0
for i in range (m):
    for j in range (n):
        sortMass[z] = genMass[i,j]
        z = z + 1
heapSort(sortMass)
z = 0
for i in range (m):
    for j in range (n):
        genMass[i,j] = sortMass[z] 
        z = z + 1
print(genMass)

[[ 1.  7.]
 [13. 16.]
 [17. 17.]
 [26. 27.]]


In [1]:
import numpy as np
def tournamentSort(Arr):
    tree = [None] * 2 * (len(Arr) + len(Arr) % 2)
    index = len(tree) - len(Arr) - len(Arr) % 2
    
    for i, v in enumerate(Arr):
        tree[index + i] = (i, v)  
    for j in range(len(Arr)):
        n = len(Arr)
        index = len(tree) - len(Arr) - len(Arr) % 2
        while index > -1:
            n = (n + 1) // 2
            for i in range(n):
                i = max(index + i * 2, 1)
                if tree[i] != None and tree[i + 1] != None:
                    if tree[i][1] < tree[i + 1][1]:
                        tree[i // 2] = tree[i]
                    else:
                        tree[i // 2] = tree[i + 1]
                else:
                    tree[i // 2] = tree[i] if tree[i] != None else tree[i + 1]
            index -= n
        index, x = tree[0]
        Arr[j] = x
        tree[len(tree) - len(Arr) - len(Arr) % 2 + index] = None
Arr = input().split()
Arr = [int(x) for x in Arr]
tournamentSort(Arr)
print(Arr)

 3 4 6 7 1 2 4


[1, 2, 3, 4, 4, 6, 7]
